force-app/main/default/objects/ProjectInvoice__c/ProjectInvoice__c.object-meta.xml
<CustomObject>
    <label>Project Invoice</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Project Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectInvoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectInvoice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>PreBill</fullName>
                <label>Pre Bill</label>
            </value>
            <value>
                <fullName>PostExecution</fullName>
                <label>Post Execution</label>
            </value>
            <value>
                <fullName>Reconcile</fullName>
            </value>
            <value>
                <fullName>Purchase Card</fullName>
                <isActive>false</isActive>
                <label>Purchase Card</label>
            </value>
            <value>
                <fullName>Third Party</fullName>
                <isActive>false</isActive>
                <label>Third Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectInvoiceLineItem__c/ProjectInvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Project Invoice Line Item</label>
    <nameField>
        <displayFormat>INVLI-{000000000}</displayFormat>
        <label>Project Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectInvoiceLineItem__c/fields/LawsonSubAccount2__c.field-meta.xml
<CustomField>
    <fullName>LawsonSubAccount2__c</fullName>
    <label>Lawson Sub Account</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectInvoiceLineItem__c/fields/ServiceType__c.field-meta.xml
<CustomField>
    <fullName>ServiceType__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>SalesTax</fullName>
            </value>
            <value>
                <fullName>Unreconciled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectInvoiceLineItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Usage</fullName>
            </value>
            <value>
                <fullName>Lumpsum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectInvoiceLineItemDetail__c/ProjectInvoiceLineItemDetail__c.object-meta.xml
<CustomObject>
    <label>Project Invoice Line Item Detail</label>
    <nameField>
        <displayFormat>PILID-{000000000}</displayFormat>
        <label>Project Invoice Line Item Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Invoice Line Items Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectInvoiceLineItemDetail__c/fields/SalesTax__c.field-meta.xml
<CustomField>
    <fullName>SalesTax__c</fullName>
    <formula>LaborTaxRate__c * (Rate__c / 100)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SalesTax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchProcessSalesTaxInvoice.cls
global class BatchProcessSalesTaxInvoice implements Database.Batchable<sObject>, Database.Stateful {
    
	Set<String> clearedpis = new Set<String>();
    global BatchProcessSalesTaxInvoice() {

        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        system.debug('BatchProcessSalesTaxInvoice Batch Started');
        
        return Database.getQueryLocator([SELECT Id, Name, ProjectInvoice__c FROM ProjectInvoiceLineItem__c WHERE 
                                         ServiceType__c = :CONSTANTS.PROJECT_INVOICE_LINEITEM_SERVICETYPE_LABOR AND
                                         ProjectInvoice__r.Status__c = :CONSTANTS.PROJECT_INVOICE_STATUS_CREATED
                                        ]);        
        
    }
   
    global void execute(Database.BatchableContext BC, List<ProjectInvoiceLineItem__c> scope) {
        
        List<ProjectInvoiceLineItem__c> newpilis = new List<ProjectInvoiceLineItem__c>();
        ProjectInvoiceLineItem__c pili = scope[0];
        //Check if there's an existing Line Item for SalesTax and remove it
        if (!clearedpis.contains(pili.ProjectInvoice__c))
        {
            delete [SELECT Id FROM ProjectInvoiceLineItem__c WHERE ProjectInvoice__c = :pili.ProjectInvoice__c AND 
                    ServiceType__c = :CONSTANTS.PROJECT_INVOICE_LINEITEM_SERVICETYPE_SALESTAX];
			clearedpis.add(pili.ProjectInvoice__c);
        }
        
        AggregateResult[] aggresults = [SELECT LaborTaxLawsonID__c, SUM(SalesTax__c) total FROM ProjectInvoiceLineItemDetail__c 
                                 		WHERE ProjectInvoiceLineItem__c = :pili.Id AND LaborTaxLawsonID__c != null 
                                        GROUP BY LaborTaxLawsonID__c HAVING SUM(SalesTax__c) > 0];
        
        for (AggregateResult ar : aggresults)  {
            string lawsontaxid = ar.get(CONSTANTS.CURRENTNAMESPACEPREFIX + 'LaborTaxLawsonID__c') == null? '':String.valueof(ar.get(CONSTANTS.CURRENTNAMESPACEPREFIX + 'LaborTaxLawsonID__c'));
            string lawsonsubaccount = lawsontaxid.right(3);
            ProjectInvoiceLineItem__c newpili = new ProjectInvoiceLineItem__c();
            newpili.ProjectInvoice__c = pili.ProjectInvoice__c;
            newpili.Description__c = 'Salestax for: ' + lawsontaxid; 
            newpili.Type__c = Constants.PROJECT_INVOICE_LINEITEM_TYPE_LUMPSUM;
            newpili.ServiceType__c = Constants.PROJECT_INVOICE_LINEITEM_SERVICETYPE_SALESTAX;
            newpili.Amount__c = ar.get('total') == null? 0:Decimal.valueOf(String.valueof(ar.get('total')));
            newpili.Rate__c = ar.get('total') == null? 0:Decimal.valueOf(String.valueof(ar.get('total')));
            newpili.LawsonSubAccount2__c = lawsonsubaccount;
            newpilis.add(newpili);
        }

		insert newpilis;        
    }

   	global void finish(Database.BatchableContext BC) {
    
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];    
        
        if (a.NumberOfErrors == 0)
        {
	        system.debug('BatchProcessSalesTaxInvoice Finished');
        }
   }    
}